### ISSUE TITLE
Where/how is RP_PROFILES used?

### ISSUE THREAD

**Issue by ringods** [reportportal/service-api#308]
Hello,

To set the context, I want to refer first to this issue:

https://github.com/reportportal/service-authorization/issues/31

I'm also in need of deploying to AWS and would favour ECS service discovery over an additional Consul container. In the configuration of the [Additional Arguments](https://github.com/reportportal/documentation/blob/master/src/md/src/InstallationSteps/AdditionalConfigurationParameters.md), I read about the `RP_PROFILES` environment variable which needs to be set to `docker`. A [search for `RP_PROFILES` in the Github `reportportal` organization](https://github.com/search?q=org%3Areportportal+RP_PROFILES) does not render many hits. None of these hits is in the code. 😕 

Given that only the value of `docker` is documented, and the Installation Documentation heavily points to the Docker Compose setup, I starting to think that this config setting matches to a `config loader` dedicated to the Docker Compose setup with all the assumptions of the Docker bridged network etc.

So if we want to support other deployment models, should other `config loaders` be implemented? If so, can someone from the ReportPortal shed light how the bootstrapping works?

Tnx.

**Comment by avarabyeu** [comment]
@ringods RP_PROFILES is used internally in our organization. Any property can be overridden via either ENV or JVM variables.

**Comment by ringods** [comment]
@avarabyeu I'm a bit disappointed with your answer. Does this mean that ReportPortal is not open for other deployment methods? Just single machine docker with bridge networking in between?

**Comment by vishallanke** [comment]
Since last few days, I am trying to solve a problem. I posted it on various forums , however, I did not receive any answer. So, I  thought to post it here.
I want to -
1 - Install complete ReportPortal on ECS (AWS Container) [We do not want to use EC2 Instance for deployment]
2 - Postgres DB should not be in same container. Host it separately, might be in container or AWS DB [ Again no EC2 Instance]
3 - Then, I want to Integrate ReportPortal and Postgres
Inside DockerHub, there are docker images for various services like authorization, UI etc. I pull one of the image(service-ui) and deploy it inside AWS container. ReportPortal UI gets opened. However, it seems  need to deploy other services like Authorization, Analyser etc.  However, I did  not find any document which will help me setting up complete ReportPortal in ECS.
Is it possible to deploy ReportPortal  in ECS and if yes, then can anyone share any link ?
